# Generated by Django 4.1.5 on 2023-01-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizName',
            new_name='Quiz_Category',
        ),
        migrations.AlterModelTable(
            name='quiz_category',
            table='Quiz_Category',
        ),
    ]
