# Generated by Django 4.1.5 on 2023-01-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_rename_quizname_quiz_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('topic_content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'General_Knowledge',
            },
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quiz_app.quiz_category'),
        ),
    ]
